version: '3'
services:
  frontend:
    build: ./frontend
    env_file:
      - .env      
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    env_file:
      - .env     
    expose:
      - "9000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

